-- MySQL Script generated by MySQL Workbench
-- Tue Jan  5 10:44:09 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Marker`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`,`Marker` (
  `idMarker` INT NOT NULL,
  PRIMARY KEY (`idMarker`),
  FULLTEXT INDEX `Farbe` () )
ENGINE = InnoDB
PACK_KEYS = DEFAULT
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `mydb`.`Ortschaften`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`,`Ortschaften` (
  `idOrtschaften` INT NOT NULL,
  PRIMARY KEY (`idOrtschaften`),
  FULLTEXT INDEX `Name` (),
  FULLTEXT INDEX `Postleitzahl` ())
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Lernende`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`,`Lernende` (
  `idLernende` INT NOT NULL,
  `Ortschaften_idOrtschaften` INT NOT NULL,
  `Marker_idMarker` INT NOT NULL,
  PRIMARY KEY (`idLernende`),
  FULLTEXT INDEX `Nachname` () ,
  INDEX `fk_Lernende_Ortschaften1_idx` (`Ortschaften_idOrtschaften` ASC) ,
  INDEX `fk_Lernende_Marker1_idx` (`Marker_idMarker` ASC) ,
  FULLTEXT INDEX `Vorname` () ,
  CONSTRAINT `fk_Lernende_Ortschaften1`
    FOREIGN KEY (`Ortschaften_idOrtschaften`)
    REFERENCES `mydb`.`Ortschaften` (`idOrtschaften`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Lernende_Marker1`
    FOREIGN KEY (`Marker_idMarker`)
    REFERENCES `mydb`.`Marker` (`idMarker`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
